In [1]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np
import pandas as pd
import pickle
from sklearn import metrics

In [2]:
# Load the dataset
iris = load_iris()

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
# Create the dataframe
df_features = pd.DataFrame(data = iris.data, columns = iris.feature_names)

df_target = pd.DataFrame(data = iris.target, columns = ['species'])

final = pd.concat([df_features, df_target], axis = 1)

# Save the Dataframe into a CSV file
final.to_csv('iris.csv', index = False)

final = pd.read_csv('iris.csv')

In [4]:
final

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [5]:
X = np.array(final.iloc[:, :4]) # Predictors 
Y = np.array(final['species']) # Target

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, Y,
                                                    stratify = Y, 
                                                    random_state = 42)

In [7]:
X_train[0:5]

array([[7.4, 2.8, 6.1, 1.9],
       [7.7, 2.8, 6.7, 2. ],
       [5.5, 2.4, 3.7, 1. ],
       [6.1, 2.8, 4. , 1.3],
       [5.5, 2.5, 4. , 1.3]])

In [8]:
y_train[0:5]

array([2, 2, 1, 1, 1])

In [9]:
# Base estimators

estimators = [('rf', RandomForestClassifier(n_estimators = 10, random_state = 42)),
              ('svr', make_pipeline(StandardScaler(), LinearSVC(random_state = 42)))]

In [10]:
# Meta Model stacked on top of base estimators

clf = StackingClassifier(estimators = estimators, final_estimator = LogisticRegression())

In [11]:
# Fit the model on traing data

stacking = clf.fit(X_train, y_train)

In [12]:
# Accuracy

stacking.score(X_test, y_test)

0.9473684210526315

In [13]:
# Save the Stacking model 
pickle.dump(stacking, open('stacking_iris.pkl', 'wb'))

In [14]:
# Load the saved model

model = pickle.load(open('stacking_iris.pkl', 'rb'))
model

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(n_estimators=10,
                                                       random_state=42)),
                               ('svr',
                                Pipeline(steps=[('standardscaler',
                                                 StandardScaler()),
                                                ('linearsvc',
                                                 LinearSVC(random_state=42))]))],
                   final_estimator=LogisticRegression())

In [15]:
# Load test dataset
test = pd.read_csv(r'C:\Users\Bharani Kumar\Desktop\Data Science using Python & R\Version 2 slides\stacking_classify_flask_new\stacking_classify_flask_new\iris_test.csv')
test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 4.9               3.1                1.5               0.1
1                 5.4               3.7                1.5               0.2
2                 4.8               3.4                1.6               0.2
3                 4.8               3.0                1.4               0.1
4                 4.3               3.0                1.1               0.1
5                 5.8               4.0                1.2               0.2
6                 5.7               4.4                1.5               0.4
7                 6.2               2.9                4.3               1.3
8                 5.1               2.5                3.0               1.1
9                 5.7               2.8                4.1               1.3
10                6.3               3.3                6.0               2.5
11                5.8               2.7                5.1               1.9
12                7.1               3.0                5.9               2.1
13                6.3               2.9                5.6               1.8
14                7.4               2.8                6.1               1.9
15                7.9               3.8                6.4               2.0
16                6.4               2.8                5.6               2.2
17                6.3               2.8                5.1               1.5
18                6.1               2.6                5.6               1.4
19                7.7               3.0                6.1               2.3
20                6.3               3.4                5.6               2.4

In [16]:
pred = model.predict(test)

C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [17]:
pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2])

In [18]:
y_test

array([0, 1, 1, 1, 0, 1, 2, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1,
       2, 1, 2, 1, 0, 2, 0, 1, 2, 2, 0, 0, 0, 0, 2, 1])

In [ ]:
# score = metrics.accuracy_score(y_test, pred)
# score